"""add_terms_to_tender

Revision ID: 1cafd6f33732
Revises: ce923f88a533
Create Date: 2025-11-27 20:08:25.971385

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1cafd6f33732"
down_revision: Union[str, None] = "ce923f88a533"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenders",
        sa.Column(
            "terms",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenders", "terms")
    # ### end Alembic commands ###
