"""Add server default to updated_at

Revision ID: a02e6a504631
Revises: a7529c1f184c
Create Date: 2025-11-26 04:36:57.646461

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a02e6a504631"
down_revision: Union[str, None] = "a7529c1f184c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tenders", "updated_at", server_default=sa.func.now())
    op.alter_column("positions", "updated_at", server_default=sa.func.now())
    op.alter_column("positions", "created_at", server_default=sa.func.now())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tenders", "updated_at", server_default=None)
    op.alter_column("positions", "updated_at", server_default=None)
    op.alter_column("positions", "created_at", server_default=None)
    # ### end Alembic commands ###
