"""link_position_to_nomenclature

Revision ID: fa2b1697a009
Revises: 6b8afc3adf52
Create Date: 2025-11-26 06:23:14.139245

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa2b1697a009"
down_revision: Union[str, None] = "6b8afc3adf52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "positions", "nomenclatures", ["nomenclature_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "positions", type_="foreignkey")
    # ### end Alembic commands ###
